language: node_js
node_js:
  - stable
install:
  - npm install -g browserify
  - npm install
script:
  - npm run make-gh-pages
env:
  global:
    - GH_REF: github.com/DrPaulBrewer/robot-trading-webapp
    - secure: >-
        htgF1CiLV67hjZWD2Hsnp1tJUS3C5zH6zlU9yqTECtepo+WzHXAuGS9BEvEG0tcXkVbygg4sk7Y9amkJxhcvllDsYqy0sHfQW3oUR/0EwZmlTyjHZViuTHP/MCh4R7yxL9l8Bzws4hdLmUSa83SRWqdtknfdF1YRxicSHmAnrvyoGfO1aYFYKSjSVDRwxL9+4zRhM3AYhy0hXrt3posOXQlMroZcFgbaVym4M1/F/Uwe9nmFq66UAITAMKuqEKPsQNsvWprnIjBcTZyqFJ4OWhXNXWmCoLGTtOsRKe5IyBYO1o3Pk+ui5SiYhaHD5EmwFTDy4AWzzRJBAMheklUS16aGNzBXF+OE2/0iyuSFtKfrRNfNpbTKgXz0lQp0iKZ1rvdV13GoZjJN0ArObICj5BDYxBlv669Zv0guTcfB7Ow5bTrnQ0xcFZwFARyU1baMDrN4TKIELJAys5UsOonzFR4rkv/PcxeSJ7dGjrcytLvZQus1T+Bt1dAELDuu4AL7AMlUgQWiC5nzY0m0NzQC3VNSyLnA28ESKgI4Rgy3+aocW5WRsJXbWGvJJ7vJx5YsUcGeKDUtPiaQ8tVMgCa3yRzXYR8xH3yybOLBnJj2z12O3ItF7u0pP4i7YJWygK3V3YNFR8+66c7pE5RwvqFkWFgkOxiWu+goYkttXUDG6Nc=
